### PR TITLE
Lexer without extra features

### PR DESCRIPTION
**Pull request by nixpulvis**
This is a working lexer, without the unified ident/keyword lookup table. Line/position tracking is working, and comments and escapes seem to be right as well.

### CODE REVIEW

**Comment by soelgary** [comment]
I am getting this when I run the tests...

```
#### TEST STATISTICS ####
PASSED: 7
FAILED: 10
#### END TEST STATISTICS ####
```

Are these known bugs?

After looking at the failures, it appears the position tracking is off by 1

**Comment by nixpulvis** [comment]
You need to manually edit the `tiger.lex.sml` file. Read the README for exactly how.

**Comment by soelgary** [comment]
Weird. Is that just the start position for `yypos` that is set by default by ml-lex?

**Comment by nixpulvis** [comment]
Yea it's fucking stupid. But left that was for backwards compatibility reasons.

**Comment by soelgary** [comment]
When I run the lexer on a file with the contents `var a = "hello world`, the returned value is `val it = [VAR (1,4),ID ("a",5,6),EQ (7,8),EOF]`. Shouldn't this raise an exception because the string is not closed?

Or will this be left to the parser?

**Comment by nixpulvis** [comment]
Your right. Should be an error. Write a test case for that, fixing it should be pretty easy. Just a check somewhere I would think.

**Comment by nixpulvis** [comment]
Yea basically a check in the `eof` function. Ideally there would be a way to ask in that fucnctio what state we are in I.e. Not any state other than INITIAL, but otherwise we could add some state to track this.

**Comment by nixpulvis** [comment]
:tada: :ship: :balloon:

**Pull request merged**
